blank_issues_enabled: false
contact_links:
  - name: Internal Discussions
    url: https://github.com/metatrom-ag/.github-private/discussions
    about: Use internal discussions for questions, not issues
